var Events = {
    INVENTORY_CREATED: 'INVENTORY_CREATED',
    INVENTORY_UPDATED: 'INVENTORY_UPDATED',
    INVENTORY_DELETED: 'INVENTORY_DELETED',
    INVENTORY_PRODUCT_INSERTED: 'INVENTORY_PRODUCT_INSERTED'
};

module.exports = Events;