var Events = {
    INVENTORY_CREATED: 'INVENTORY_CREATED',
    INVENTORY_UPDATED: 'INVENTORY_UPDATED',
    INVENTORY_DELETED: 'INVENTORY_DELETED',
    INVENTORY_PRODUCT_INSERTED: 'INVENTORY_PRODUCT_INSERTED',
    INVENTORY_PRODUCT_DELETED: 'INVENTORY_PRODUCT_DELETED',
    PRODUCT_ADDED_TO_INVENTORY: 'PRODUCT_ADDED_TO_INVENTORY',
    PRODUCT_REMOVED_FROM_INVENTORY: 'PRODUCT_REMOVED_FROM_INVENTORY',
};

module.exports = Events;