var ServerEvents = {
    FIND_ALL_INVENTORIES: 'FIND_ALL_INVENTORIES',
    FIND_ALL_INVENTORY_PRODUCTS: 'FIND_ALL_INVENTORY_PRODUCTS',
    FIND_INVENTORY: 'FIND_INVENTORY',
    CREATE_INVENTORY: 'CREATE_INVENTORY',
    UPDATE_INVENTORY: 'UPDATE_INVENTORY',
    DELETE_INVENTORY: 'DELETE_INVENTORY',
    INSERT_INVENTORY_PRODUCT: 'INSERT_INVENTORY_PRODUCT',
    DELETE_INVENTORY_PRODUCT: 'DELETE_INVENTORY_PRODUCT'
};

module.exports = ServerEvents;