var ServerEvents = {
    FIND_ALL_INVENTORIES: 'FIND_ALL_INVENTORIES',
    FIND_INVENTORY: 'FIND_INVENTORY',
    CREATE_INVENTORY: 'CREATE_INVENTORY',
    UPDATE_INVENTORY: 'UPDATE_INVENTORY',
    DELETE_INVENTORY: 'DELETE_INVENTORY'
};

module.exports = ServerEvents;