var ServerEvents = {
    FIND_ALL_INVENTORIES: 'FIND_ALL_INVENTORIES',
    FIND_ALL_INVENTORY_PRODUCTS: 'FIND_ALL_INVENTORY_PRODUCTS',
    FIND_INVENTORY: 'FIND_INVENTORY',
    CREATE_INVENTORY: 'CREATE_INVENTORY',
    UPDATE_INVENTORY: 'UPDATE_INVENTORY',
    DELETE_INVENTORY: 'DELETE_INVENTORY',
    INSERT_INVENTORY_PRODUCT: 'INSERT_INVENTORY_PRODUCT',
    DELETE_INVENTORY_PRODUCT: 'DELETE_INVENTORY_PRODUCT',
    ADD_PRODUCT_TO_INVENTORY: 'ADD_PRODUCT_TO_INVENTORY',
    REMOVE_PRODUCT_FROM_INVENTORY: 'REMOVE_PRODUCT_FROM_INVENTORY',
    EDIT_INVENTORY_PRODUCT_QUANTITY: 'EDIT_INVENTORY_PRODUCT_QUANTITY'
};

module.exports = ServerEvents;