var ServerEvents = {
    FIND_ALL_PRODUCTS: 'FIND_ALL_PRODUCTS',
    FIND_PRODUCT: 'FIND_PRODUCT',
    FIND_PRODUCT_DECOMPOSED: 'FIND_PRODUCT_DECOMPOSED',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT'
};

module.exports = ServerEvents;