var Events = {
    SELL_CREATED: 'SELL_CREATED',
    SELL_UPDATED: 'SELL_UPDATED',
    SELL_DELETED: 'SELL_DELETED',

    TRACK_CREATED: 'TRACK_CREATED',
    TRACK_UPDATED: 'TRACK_UPDATED'
};

module.exports = Events;