var ServerEvents = {
    FIND_ALL_SELLS: 'FIND_ALL_SELLS',
    FIND_SELL: 'FIND_SELL',
    CREATE_SELL: 'CREATE_SELL',
    UPDATE_SELL: 'UPDATE_SELL',
    DELETE_SELL: 'DELETE_SELL',

    FIND_ALL_TRACKS: 'FIND_ALL_TRACKS',
    FIND_TRACK: 'FIND_TRACK',
    CREATE_TRACK: 'CREATE_TRACK',
    UPDATE_TRACK: 'UPDATE_TRACK'
};

module.exports = ServerEvents;